# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Delete rule output on recipe failure.
.DELETE_ON_ERROR:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/cooldude101/ExoskeletonAI/software/test

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/cooldude101/ExoskeletonAI/software/test

# Include any dependencies generated for this target.
include CMakeFiles/../ExoSAI.dir/depend.make

# Include the progress variables for this target.
include CMakeFiles/../ExoSAI.dir/progress.make

# Include the compile flags for this target's objects.
include CMakeFiles/../ExoSAI.dir/flags.make

CMakeFiles/../ExoSAI.dir/test_node.cpp.o: CMakeFiles/../ExoSAI.dir/flags.make
CMakeFiles/../ExoSAI.dir/test_node.cpp.o: test_node.cpp
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/home/cooldude101/ExoskeletonAI/software/test/CMakeFiles --progress-num=$(CMAKE_PROGRESS_1) "Building CXX object CMakeFiles/../ExoSAI.dir/test_node.cpp.o"
	/usr/bin/c++   $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -o CMakeFiles/../ExoSAI.dir/test_node.cpp.o -c /home/cooldude101/ExoskeletonAI/software/test/test_node.cpp

CMakeFiles/../ExoSAI.dir/test_node.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/../ExoSAI.dir/test_node.cpp.i"
	/usr/bin/c++  $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /home/cooldude101/ExoskeletonAI/software/test/test_node.cpp > CMakeFiles/../ExoSAI.dir/test_node.cpp.i

CMakeFiles/../ExoSAI.dir/test_node.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/../ExoSAI.dir/test_node.cpp.s"
	/usr/bin/c++  $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /home/cooldude101/ExoskeletonAI/software/test/test_node.cpp -o CMakeFiles/../ExoSAI.dir/test_node.cpp.s

CMakeFiles/../ExoSAI.dir/test_node.cpp.o.requires:

.PHONY : CMakeFiles/../ExoSAI.dir/test_node.cpp.o.requires

CMakeFiles/../ExoSAI.dir/test_node.cpp.o.provides: CMakeFiles/../ExoSAI.dir/test_node.cpp.o.requires
	$(MAKE) -f CMakeFiles/../ExoSAI.dir/build.make CMakeFiles/../ExoSAI.dir/test_node.cpp.o.provides.build
.PHONY : CMakeFiles/../ExoSAI.dir/test_node.cpp.o.provides

CMakeFiles/../ExoSAI.dir/test_node.cpp.o.provides.build: CMakeFiles/../ExoSAI.dir/test_node.cpp.o


# Object files for target ../ExoSAI
__/ExoSAI_OBJECTS = \
"CMakeFiles/../ExoSAI.dir/test_node.cpp.o"

# External object files for target ../ExoSAI
__/ExoSAI_EXTERNAL_OBJECTS =

../ExoSAI: CMakeFiles/../ExoSAI.dir/test_node.cpp.o
../ExoSAI: CMakeFiles/../ExoSAI.dir/build.make
../ExoSAI: /usr/lib/libgtest.a
../ExoSAI: CMakeFiles/../ExoSAI.dir/link.txt
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --bold --progress-dir=/home/cooldude101/ExoskeletonAI/software/test/CMakeFiles --progress-num=$(CMAKE_PROGRESS_2) "Linking CXX executable ../ExoSAI"
	$(CMAKE_COMMAND) -E cmake_link_script CMakeFiles/../ExoSAI.dir/link.txt --verbose=$(VERBOSE)

# Rule to build all files generated by this target.
CMakeFiles/../ExoSAI.dir/build: ../ExoSAI

.PHONY : CMakeFiles/../ExoSAI.dir/build

CMakeFiles/../ExoSAI.dir/requires: CMakeFiles/../ExoSAI.dir/test_node.cpp.o.requires

.PHONY : CMakeFiles/../ExoSAI.dir/requires

CMakeFiles/../ExoSAI.dir/clean:
	$(CMAKE_COMMAND) -P CMakeFiles/../ExoSAI.dir/cmake_clean.cmake
.PHONY : CMakeFiles/../ExoSAI.dir/clean

CMakeFiles/../ExoSAI.dir/depend:
	cd /home/cooldude101/ExoskeletonAI/software/test && $(CMAKE_COMMAND) -E cmake_depends "Unix Makefiles" /home/cooldude101/ExoskeletonAI/software/test /home/cooldude101/ExoskeletonAI/software/test /home/cooldude101/ExoskeletonAI/software/test /home/cooldude101/ExoskeletonAI/software/test /home/cooldude101/ExoskeletonAI/software/test/ExoSAI.dir/DependInfo.cmake --color=$(COLOR)
.PHONY : CMakeFiles/../ExoSAI.dir/depend

